spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=GMT%2B8
    username: Allan
    password: NoT5gvYc6mQwecBwpSrFLCroY55bEZ5iinTxn8FFvYlEvDtT1neRd+9S6mCUfpRwZQYGpAxUVCK2AjrP94AFJw==
    # 配置 connection-properties，启用加密，配置公钥。
    connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey};password=${spring.datasource.password};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 公钥
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKO8LPbFolNZgCfo+lXpnBddb7tydexpQJxxTdLpfLhV4wSeA8+fMVipkEogTmrJ0ucyPuIPoVrsW4KVE75PCTkCAwEAAQ==
    initial-size: 5
    max-active: 10
    min-idle: 2
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxOpenPreparedStatements: 10
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #有两个含义：1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 1800000
  druid:
    #当数据库抛出一些不可恢复的异常时，抛弃连接
    exceptionSorter: com.alibaba.druid.pool.vendor.MySqlExceptionSorter
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    filters: stat,log4j2,wall,config
    #数据库密码解密使用的类
    password-callback: com.alibaba.druid.util.DruidPasswordCallback

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9589

#logging:
#  config: xxxx.xml